spring:
  application:
    name: order-shipment
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta_express
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
#      defaultZone: http://server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/