version: '3.8'

services:
  server:
    build:
      context: ./com.sparta-express.server
    image: server
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./com.sparta-express.gateway
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - company-product
      - order-shipment

  company-product:
    build:
      context: ./com.sparta-express.company-product
    image: company-product
    ports:
      - "8081:8081"
    depends_on:
      - server

  order-shipment:
    build:
      context: ./com.sparta-express.order-shipment
    image: order-shipment
    ports:
      - "8082:8082"
    depends_on:
      - server

  hub:
    build:
      context: ./com.sparta-express.hub
    image: hub
    ports:
      - "8084:8084"
    depends_on:
      - server


networks:
  default:
    driver: bridge