spring:
  application:
    name: hub
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/hub  # local url
    url: jdbc:postgresql://43.203.205.156:5432/hub_db    #공용 url
    platform: postgres
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

naver:
  api:
    client:
      id: ${NAVER_API_CLIENT_ID}
      secret: ${NAVER_API_CLIENT_SECRET}

logging:
  level:
    org:
      hibernate:
        engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG
        SQL: DEBUG
      springframework:
        beans.factory: DEBUG
        jdbc.datasource: DEBUG
