spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order-shipment
          uri: lb://order-shipment
          predicates:
            - Path=/orders/**

        - id: company-product
          uri: lb://company-product
          predicates:
            - Path=/companies/**, /products/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://server:8761/eureka/