spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-shipment
          predicates:
            - Path=/api/orders/**

        - id: order-shipments
          uri: lb://order-shipment
          predicates:
            - Path=/api/shipments/**

        - id: order-shipmentRoutes
          uri: lb://order-shipment
          predicates:
            - Path=/api/shipmentRoutes/**

        - id: company-product
          uri: lb://company-product
          predicates:
            - Path=/companies/**, /products/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

service:
  jwt:
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1