spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order-shipment
          uri: lb://order-shipment
          predicates:
            - Path=/orders/**

        - id: company-product
          uri: lb://company-product
          predicates:
            - Path=/companies/**, /products/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: ai-slack
          uri: lb://ai-slack
          predicates:
            - Path=/api/v1/ai/**
            - Path=/api/v1/slack/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

service:
  jwt:
    secret-key: ${SECRET_KEY}