spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${SECRET_KEY}

server:
  port: 8083